### ISSUE TITLE
There is some error with zphofile:16 

### ISSUE THREAD

**Issue by ApolonHellas** [AshMagill/mernrod#9]
![IMG_20220619_091513](https://user-images.githubusercontent.com/12831445/174470135-8ad74410-913b-4f60-a6df-162473abce63.jpg)
![IMG_20220619_091453](https://user-images.githubusercontent.com/12831445/174470136-aeb2ef2a-aa6f-46e5-91a3-c72528518966.jpg)

**Comment by AshMagill** [comment]
So it was just a typo in .config/shell/profile
I have just pushed my changes to github and tested it and it works, so everything should be ok now.
If you run the shell script again it will install very quickly (because everything is already downloaded).

**Comment by ApolonHellas** [comment]
It's fine know ty
